### PR TITLE
Fix some return types

### PR DESCRIPTION
**Pull request by gRoussac**
Trying to narrow a reason for this [ApiError::EarlyEndOfStream [17]](https://testnet.cspr.live/deploy/a18892a4934d94ef2bd60b4274851cce85aaaac6826acdb636869637612a6b00)

### CODE REVIEW

**Comment by gRoussac** [comment]
@bufo24

**Comment by bufo24** [comment]
Thanks for creating this PR! I will test it

**Comment by gRoussac** [comment]
@bufo24 thanks! if error still happens, then please check where returns are used and types etc, try to see where the return of ENTRY_POINT_EXECUTE_LISTING is used likes execute_listing_session/src/main.rs

**Comment by bufo24** [comment]
still happens on your branch when calling `add_listing`

**Comment by gRoussac** [comment]
@bufo24 Early end of stram means a return type is not correct.

Can you please try this commit 

https://github.com/BitHotelOrg/bithotel-casper-contracts/commit/cf394e82b478a361d41ca9d75ebfcbf3ef274871

and please check every expected type are well defined in every entry point further

**Comment by bufo24** [comment]
Will check

**Comment by gRoussac** [comment]
Unlucky, sorry can you please check again you recompiled and deploy the right contract becasue your last attempt was targeting contract hash-d7fe9f819cd6a99034063a34a3e6073aa839e88cc89d7c7424da2653dffe93b7 which still has a bad entrypoint types
 ```json
{
        "access": "Public",
        "entryPointType": "Contract",
        "name": "add_listing",
        "ret": "Unit",
        "args": [
          {
            "name": "collection",
            "clType": "Key"
          },
          {
            "name": "token_id",
            "clType": "U256"
          },
          {
            "name": "price",
            "clType": "U256"
          }
        ]
      },
      
 ```
      
      
Contract-CSPR-live

**Comment by gRoussac** [comment]
What I don't get is why a test is not triggered when 

```
#[test]
fn should_not_add_listing_0() {
    let (mut builder, marketplace_contract_hash, nft_contract_hash) = deploy_with_nft(true);

    let marketplace = MarketplaceInstance::new(marketplace_contract_hash);
    marketplace.add_listing(
        &mut builder,
        *DEFAULT_ACCOUNT_ADDR,
        nft_contract_hash,
        5u64,
        U256::from(10u64),
        false,
    );
}
```

with this misstype https://github.com/BitHotelOrg/bithotel-casper-contracts/blob/main/marketplace/contract/src/marketplace.rs#L335

You should see this end of stream in this test.

I suspect an issue when testing `pub(crate) const MARKETPLACE: &str = "marketplace.wasm";`

Please see my last [commit](https://github.com/BitHotelOrg/bithotel-casper-contracts/pull/10/commits/ffc66602fc8df2e64a72249057562ba5f2f734c4) 

This test should fail with early end of stream too obviously.

**Comment by bufo24** [comment]
Redeployed the compiled version and still the errors occurs. Also just tried your last commit and the tests all pass. Does the `should_add_listing` test fail for you?

**Comment by gRoussac** [comment]
It seems the error is coming from the nft because I don't trigger the error when calling my self your contract (probably I am not approved)

https://testnet.cspr.live/deploy/270c24c09d79ac10717a760384168baa80a02f2c54066abb73f36b98edf74498

So I am suspecting this the transfer method has return type issues. I don't get why tests are not reproducing.

please check that commit https://github.com/BitHotelOrg/bithotel-casper-contracts/pull/10/commits/051a3a84daeb9298c8a98c0cfda0df90ddb5486f

**Comment by bufo24** [comment]
Ah that's interesting! 
Will check for myself and test

**Comment by bufo24** [comment]
Still the same error. But it's nice to know that it does not happen when you are not the NFT holder. I will continue tomorrow on this with testing different cases so narrow down to the problem. Thanks for your help so far!

**Comment by gRoussac** [comment]
Ok last test now would be now to comment out nft.transfer() call and see if the rest of the code still triggers an early end of stream without it.
```
    let test =  nft.get_approved(caller.into(), token_id)
        .unwrap_or_revert_with(MarketplaceError::NFTRequireApprove);
        runtime::put_key(" TEST get_approved", test);
     // nft.transfer(caller.into(), marketplace_address.into(), token_id);
```

**Comment by Jiuhong-casperlabs** [comment]
https://testnet.cspr.live/uref/uref-27c7736f924dab9f9ddf376f20ad7d617694af0869af1743bbba5ece806bd886-007
The reporting_mode is 0 which is `OwnerReverseLookupMode::NoLookUp` so the return value logic for transfer cannot be executed. In other words, it returns nothing. 

https://github.com/casper-ecosystem/cep-78-enhanced-nft/blob/dev/contract/src/main.rs#L1277-L1297

I would remove the return value from the transfer 
```
runtime::call_contract::<()>
```

**Comment by bufo24** [comment]
> Ok last test now would be now to comment out nft.transfer() call and see if the rest of the code still triggers an early end of stream without it.
> 
> ```
>     let test =  nft.get_approved(caller.into(), token_id)
>         .unwrap_or_revert_with(MarketplaceError::NFTRequireApprove);
>         runtime::put_key(" TEST get_approved", test);
>      // nft.transfer(caller.into(), marketplace_address.into(), token_id);
> ```

Wow this worked! https://testnet.cspr.live/deploy/b8af2401a2693b4c4113cf8c6d3630ecf8de9e61510c1c2f6e62d3ed0af3a386

Putting `runtime::call_contract::<()>` on the transfer would be fixing it then I guess. Will test that now.

**Comment by gRoussac** [comment]
Good catch, it was the the opposite way around actually, I wanted to type things while they needed to be untyped ! tricky !
```
    if let OwnerReverseLookupMode::Complete | OwnerReverseLookupMode::TransfersOnly = reporting_mode
    {
    ...
            runtime::ret(receipt)
    }
```

@bufo24 I still don't understand how tests are passing because I can not find any setting regarding OwnerReverseLookupMode(reporting mode) in them, so by default it seems to me test are also using NoLookup. I would suggest to explicitly set that to Nolookup accordingly in the **tests** because it was really hard to spot a difference with production here, this end of stream would be then triggered in tests.

Also when testing a failed deploy I would strongly suggest that you fulfill your condition by a check on the error returned in your tests

something like 

```
         if should_succeed {
             builder.expect_success();
         } else {
             builder.expect_failure();

    let error = builder.get_error().expect("must have error");

    assert_expected_error(
        error,
        MarketplaceError::ContractAlreadyInitialized as u16, // here actually there error set in the param
        "should have correct error number",
    );

Please anyway merge the type differences on entrypoints u64/u256 of this PR (not int the cep78 interface thus). Try to have consistent input/output params in any case.

**Comment by bufo24** [comment]
Hey! I am back.

By putting `runtime::call_contract::<()>` on the ICEP78::transfer, the test do fail. With the (String, Key) return type, it works.

**Comment by Jiuhong-casperlabs** [comment]
> OwnerReverseLookupMode::Complete | OwnerReverseLookupMode::TransfersOnly

The point is OwnerReverseLookupMode which is set when installing contract by 
`--session-arg "owner_reverse_lookup_mode:u8='x'" \`

When it is Complete 1 or TransfersOnly 2 there is return value. (`runtime::call_contract::<(String, Key)>` should be used)
When it is NoLookUp 0 there is no return value (`runtime::call_contract::<()>` should be used)

**Comment by bufo24** [comment]
Hey @Jiuhong-casperlabs, thanks for the extra explanation regarding the OwnerReverseLookupMode, this was indeed one of the problems! I've finally got the test suite to work properly and was able to find and fix more bugs. Now everything seems to work on testnet! Thank you @Jiuhong-casperlabs and @gRoussac both for helping me out on this!

**Pull request closed without merging**
